apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    eventlistener: tinyfilemanager-github-listener-interceptor
  name: tinyfilemanager-github-listener-el
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-liberty-rest-github-listener-interceptor